name: Clippy check
on:
  push:
    branches:
      - "*"
  pull_request:
    branches:
      - "*"
jobs:
  clippy_check:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2

      - run: rustup component add clippy
      
# Workaround from https://github.com/actions-rs/clippy-check/issues/2#issuecomment-807878478
      # - name: Check workflow permissions
      #   id: check_permissions
      #   uses: scherermichael-oss/action-has-permission@1.0.6
      #   with:
      #     required-permission: write
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      # - name: Run clippy action to produce annotations
      #   uses: actions-rs/clippy-check@v1
      #   if: steps.check_permissions.outputs.has-permission
      #   with:
      #     args: --all-targets -- -D warnings
      #     token: ${{ secrets.GITHUB_TOKEN }}
      # - name: Run clippy manually without annotations
      #   if: ${{ !steps.check_permissions.outputs.has-permission }}
      #   run: cargo clippy --all-targets -- -D warnings
      - name: Run clippy manually without annotations
        run: cargo clippy --all-targets -- -D warnings